config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "habits#index"

  resources :habits do
    resources :completions, only: [ :create ]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/completion.rb
class Completion < ApplicationRecord
  belongs_to :habit

  scope :for_frequency, ->(frequency) do
    time_range = case frequency
    when "daily" then Time.current.beginning_of_day..Time.current.end_of_day
    when "weekly" then Time.current.beginning_of_week..Time.current.end_of_week
    when "monthly" then Time.current.beginning_of_month..Time.current.end_of_month
    when "annually" then Time.current.beginning_of_year..Time.current.end_of_year
    else raise ArgumentError, "'#{frequency}' is not a valid frequency"
    end

    where(completed_at: time_range)
  end

  scope :completed_today, -> { for_frequency("daily") }
  scope :completed_this_week, -> { for_frequency("weekly") }
  scope :completed_this_month, -> { for_frequency("monthly") }
  scope :completed_this_year, -> { for_frequency("annually") }
end

app/models/habit.rb
class Habit < ApplicationRecord
  validates :title, presence: true, length: { minimum: 3 }

  enum :frequency, { daily: "daily", weekly: "weekly", monthly: "monthly", annually: "annually" }, default: :daily

  has_rich_text :description
  has_many :completions, dependent: :destroy

  def completed?
    completions.for_frequency(frequency).any?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/completions_controller.rb
class CompletionsController < ApplicationController
  def create
    @habit = Habit.find(params[:habit_id])
    completion = @habit.completions.new(completed_at: Time.current)

    if completion.save
      redirect_to @habit, notice: "Habit completed successfully."
    else
      redirect_to @habit, alert: "Failed to complete habit."
    end
  end
end

app/controllers/habits_controller.rb
class HabitsController < ApplicationController
  before_action :set_habit, only: [ :show, :edit, :update, :destroy ]

  def index
    @habits = Habit.includes(:completions).group_by(&:frequency)
  end

  def show
  end

  def new
    @habit = Habit.new
  end

  def create
    @habit = Habit.new(habit_params)

    if @habit.save
      respond_to do |format|
        format.html { redirect_to habit_path(@habit), notice: "Habit was successfully created." }
      end
    else
      respond_to do |format|
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def edit
  end

  def update
    if @habit.update(habit_params)
      respond_to do |format|
        format.html { redirect_to @habit, notice: "Habit was successfully updated." }
      end
    else
      respond_to do |format|
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @habit.destroy

    respond_to do |format|
      format.html { redirect_to root_path, notice: "Habit was successfully deleted." }
    end
  end

  private

  def habit_params
    params.require(:habit).permit(:title, :frequency, :description)
  end

  def set_habit
    @habit = Habit.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    redirect_to root_path, alert: "Habit not found."
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/habits_helper.rb
module HabitsHelper
  def frequency_badge(habit)
    color_classes =
      case habit.frequency.downcase
      when "daily"
        "bg-yellow-50 text-yellow-800 ring-yellow-600/20"
      when "weekly"
        "bg-green-50 text-green-800 ring-green-600/20"
      when "monthly"
        "bg-blue-50 text-blue-800 ring-blue-600/20"
      when "yearly"
        "bg-purple-50 text-purple-800 ring-purple-600/20"
      else
        "bg-gray-50 text-gray-800 ring-gray-600/20"
      end

    content_tag(
      :span,
      habit.frequency.capitalize,
      class: "#{color_classes} inline-flex items-center rounded-md px-2 py-1 text-xs font-medium ring-1 ring-inset mb-3"
    )
  end
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/habits/_form.html.erb
<%= form_with(model: habit) do |f| %>
  <div>
    <% if habit.errors.any? %>
      <div class="mb-4">
        <ul id="habit-errors-list" class="list-disc pl-5 text-red-600">
          <% habit.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  </div>

  <div class="mb-4">
    <%= f.label :title, class: "block text-sm/6 font-medium text-gray-900" %>
    <div class="mt-2">
      <%= f.text_field :title, class: "block w-full rounded-md bg-white px-3 py-1.5 text-base text-gray-900 outline-1 -outline-offset-1 outline-gray-300 placeholder:text-gray-400 focus:outline-2 focus:-outline-offset-2 focus:outline-indigo-600 sm:text-sm/6", required: true %>
    </div>
  </div>

  <div class="mb-4">
    <%= f.label :description, class: "block text-sm/6 font-medium text-gray-900" %>
    <div class="mt-2">
      <%= f.rich_textarea :description, class: "mt-1 block w-full rounded border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm", rows: 3 %>
    </div>
  </div>

  <div class="mb-4">
    <%= f.label :frequency, class: "block text-sm/6 font-medium text-gray-900" %>
    <div class="mt-2 grid grid-cols-1">
      <%= f.select :frequency, options_for_select(Habit.frequencies.keys, { selected: habit.frequency || Habit.new.frequency }), { include_blank: true }, { class: "col-start-1 row-start-1 w-full appearance-none rounded-md bg-white py-1.5 pr-8 pl-3 text-base text-gray-900 outline-1 -outline-offset-1 outline-gray-300 focus:outline-2 focus:-outline-offset-2 focus:outline-indigo-600 sm:text-sm/6" } %>
    </div>
  </div>

  <div class="flex items-center justify-end">
    <%= f.submit "Save", class: "inline-flex items-center rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-xs hover:bg-indigo-700 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600" %>
  </div>
<% end %>

app/views/habits/_habit.html.erb
<div class="bg-white shadow-lg rounded-lg p-6">
  <div class="flex justify-between items-start mb-4">
    <h3 class="text-lg font-semibold text-gray-900">
      <%= link_to habit_path(habit), class: "underline" do %>
        <%= habit.title %>
      <% end %>
    </h3>
    <div>
      <%= frequency_badge(habit) if habit.frequency.present? %>
    </div>
  </div>
  <% if habit.description.present? %>
    <p class="text-sm text-gray-400">
      <%= habit.description.to_plain_text.truncate(50) %>
    </p>
  <% end %>
  <% if habit.completed? %>
    <div class="mt-3 flex justify-end">
      <svg class="w-6 h-6 text-green-400 dark:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" viewBox="0 0 24 24">
        <path fill-rule="evenodd" d="M2 12C2 6.477 6.477 2 12 2s10 4.477 10 10-4.477 10-10 10S2 17.523 2 12Zm13.707-1.293a1 1 0 0 0-1.414-1.414L11 12.586l-1.793-1.793a1 1 0 0 0-1.414 1.414l2.5 2.5a1 1 0 0 0 1.414 0l4-4Z" clip-rule="evenodd"/>
      </svg>
    </div>
  <% end %>
</div>

app/views/habits/edit.html.erb
<div class="mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:px-8">
  <div class="mb-3">
    <%= link_to "< Back", habit_path(@habit), class: "text-indigo-600 hover:text-indigo-900 underline" %>
  </div>
  <div>
    <h1 class="font-bold text-3xl text-gray-900 mb-6">
      Edit Habit
    </h1>
    <%= render 'form', habit: @habit %>
  </div>
</div>

app/views/habits/index.html.erb
<header>
  <div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
    <div class="md:flex md:items-center md:justify-between">
      <div class="min-w-0 flex-1">
        <h2 class="text-2xl/7 font-bold text-gray-900 sm:truncate sm:text-3xl sm:tracking-tight">
          Habits Tracker
        </h2>
      </div>
      <div class="mt-4 flex md:mt-0 md:ml-4">
        <%= link_to new_habit_path, class: "inline-flex items-center rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-xs hover:bg-indigo-700 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600" do %>
          <span>Add a habit</span>
          <svg class="ml-2 h-5 w-5" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 20" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 5v10m5-5H5" />
          </svg>
        <% end %>
      </div>
    </div>
  </div>
</header>
<main>
  <div class="mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:px-8">
    <% if @habits.any? %>
      <% @habits.each do |frequency, habits| %>
        <div class="mb-8">
          <h2 class="text-xl font-semibold text-gray-900 mb-4 capitalize">
            <%= frequency %> Habits
          </h2>
          <div class="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 items-start">
            <% habits.each do |habit| %>
              <%= render partial: "habits/habit", locals: { habit: habit } %>
            <% end %>
          </div>
        </div>
      <% end %>
    <% else %>
      <button type="button" class="relative block w-full rounded-lg border-2 border-dashed border-gray-300 p-12 text-center hover:border-gray-400 focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2 focus:outline-hidden">
        <p class="mx-auto text-4xl text-gray-400">⏱️</p>
        <span class="mt-2 block text-sm font-semibold text-gray-900">Add a habit</span>
      </button>
    <% end %>
  </div>
</main>

app/views/habits/new.html.erb
<div class="mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:px-8">
  <div class="mb-3">
    <%= link_to "< Back to Habits", root_path, class: "text-indigo-600 hover:text-indigo-900 underline" %>
  </div>
  <div>
    <%= render 'form', habit: @habit %>
  </div>
</div>

app/views/habits/show.html.erb
<div class="mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:px-8">
  <div class="mb-3">
    <%= link_to "< Back to Habits", root_path, class: "text-indigo-600 hover:text-indigo-900 underline" %>
  </div>
  <div class="flex items-start justify-between">
    <div>
      <h1 class="font-bold text-3xl text-gray-900 mb-3">
        <%= @habit.title %>
      </h1>
      <%= frequency_badge(@habit) %>
    </div>
    <div class="flex space-x-2">
      <%= button_to habit_path(@habit), method: :delete, class: "inline-flex items-center rounded-md bg-red-600 px-3 py-2 text-sm font-semibold text-white shadow-xs hover:bg-red-700 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-red-600", data: {turbo_confirm: 'Are you sure?'} do %>
        <span>Delete habit</span>
      <% end %>
      <%= link_to edit_habit_path(@habit), class: "inline-flex items-center rounded-md bg-gray-600 px-3 py-2 text-sm font-semibold text-white shadow-xs hover:bg-gray-700 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-gray-600" do %>
        <span>Edit habit</span>
      <% end %>
    </div>
  </div>
  <div class="mt-4">
    <% if @habit.description.present? %>
      <p class="text-gray-600"><%= @habit.description %></p>
    <% else %>
      <p class="text-gray-400">No description provided.</p>
    <% end %>
  </div>
  <div class="mt-6">
    <% unless @habit.completed? %>
      <%= form_with(model: [:habits, @habit.completions.new], url: habit_completions_path(@habit), method: :post) do |form| %>
        <div class="flex space-x-2">
          <%= form.submit "Complete Habit", class: "inline-flex items-center rounded-md bg-green-600 px-3 py-2 text-sm font-semibold text-white shadow-xs hover:bg-green-700 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-green-600" %>
        </div>
      <% end %>
      <div class="mt-4"></div>
        <ul class="list-disc pl-5 text-gray-700">
          <% @habit.completions.for_frequency(@habit.frequency).each do |completion| %>
            <li><%= completion.created_at.strftime("%B %d, %Y") %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="relative mt-6">
      <div aria-hidden="true" class="absolute inset-0 flex items-center">
        <div class="w-full border-t border-gray-300"></div>
      </div>
      <div class="relative flex justify-center">
        <span class="bg-white px-3 text-base font-semibold text-gray-900">Completions</span>
      </div>
    </div>

    <div class="mt-4">
      <ul class="list-none pl-5 text-gray-700">
        <% @habit.completions.for_frequency(@habit.frequency).each do |completion| %>
          <li class="flex items-center space-x-2">
            <svg class="w-6 h-6 text-green-400 dark:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" viewBox="0 0 24 24">
              <path fill-rule="evenodd" d="M2 12C2 6.477 6.477 2 12 2s10 4.477 10 10-4.477 10-10 10S2 17.523 2 12Zm13.707-1.293a1 1 0 0 0-1.414-1.414L11 12.586l-1.793-1.793a1 1 0 0 0-1.414 1.414l2.5 2.5a1 1 0 0 0 1.414 0l4-4Z" clip-rule="evenodd"/>
            </svg>
            <span>
              <%= completion.completed_at.strftime("%B %d, %Y") %>
            </span>
          </li>
        <% end %>
      </ul>
    </div>
</div>

app/views/home/index.html.erb
<header>
  <div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
    <div class="md:flex md:items-center md:justify-between">
      <div class="min-w-0 flex-1">
        <h2 class="text-2xl/7 font-bold text-gray-900 sm:truncate sm:text-3xl sm:tracking-tight">
          Habits Tracker
        </h2>
      </div>
      <div class="mt-4 flex md:mt-0 md:ml-4">
        <button type="button" class="ml-3 inline-flex items-center rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-xs hover:bg-indigo-700 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">Add habit</button>
      </div>
    </div>
  </div>
</header>
<main>
  <div class="mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:px-8">
    <!-- Your content -->
    <h1>Welcome to the Habits Tracker</h1>
  </div>
</main>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Habit Tracker" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body>
    <div class="min-h-full">
      <%= render 'shared/navbar' %>
      <%= render 'shared/flash_messages' %>

      <div class="py-10">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/shared/_flash_messages.html.erb
<% if flash.any? %>
  <% flash.each do |key, value| %>
    <div class="rounded-md bg-blue-50 p-4" data-controller="flash">
      <div class="flex">
        <div class="shrink-0">
          <svg viewBox="0 0 20 20" fill="currentColor" data-slot="icon" aria-hidden="true" class="size-5 text-blue-400">
            <path d="M18 10a8 8 0 1 1-16 0 8 8 0 0 1 16 0Zm-7-4a1 1 0 1 1-2 0 1 1 0 0 1 2 0ZM9 9a.75.75 0 0 0 0 1.5h.253a.25.25 0 0 1 .244.304l-.459 2.066A1.75 1.75 0 0 0 10.747 15H11a.75.75 0 0 0 0-1.5h-.253a.25.25 0 0 1-.244-.304l.459-2.066A1.75 1.75 0 0 0 9.253 9H9Z" clip-rule="evenodd" fill-rule="evenodd" />
          </svg>
        </div>
        <div class="ml-3 flex-1 md:flex md:justify-between">
          <p class="text-sm text-blue-700">
            <%= value %>
          </p>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="border-b border-gray-200 bg-white">
  <div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
    <div class="flex h-16 justify-between">
      <div class="flex">
        <div class="flex shrink-0 items-center">
          <span class="block h-8 w-auto lg:hidden text-4xl">⏱️</span>
          <span class="hidden h-8 w-auto lg:block text-4xl">⏱️</span>
        </div>
        <div class="hidden sm:-my-px sm:ml-6 sm:flex sm:space-x-8">
          <!-- Current: "border-indigo-500 text-gray-900", Default: "border-transparent text-gray-500 hover:border-gray-300 hover:text-gray-700" -->
          <a href="#" class="inline-flex items-center border-b-2 border-indigo-500 px-1 pt-1 text-sm font-medium text-gray-900" aria-current="page">Dashboard</a>
        </div>
      </div>
      <div class="-mr-2 flex items-center sm:hidden">
        <!-- Mobile menu button -->
        <button type="button" class="relative inline-flex items-center justify-center rounded-md bg-white p-2 text-gray-400 hover:bg-gray-100 hover:text-gray-500 focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2 focus:outline-hidden" aria-controls="mobile-menu" aria-expanded="false">
          <span class="absolute -inset-0.5"></span>
          <span class="sr-only">Open main menu</span>
          <!-- Menu open: "hidden", Menu closed: "block" -->
          <svg class="block size-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true" data-slot="icon">
            <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5" />
          </svg>
          <!-- Menu open: "block", Menu closed: "hidden" -->
          <svg class="hidden size-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true" data-slot="icon">
            <path stroke-linecap="round" stroke-linejoin="round" d="M6 18 18 6M6 6l12 12" />
          </svg>
        </button>
      </div>
    </div>
  </div>

  <!-- Mobile menu, show/hide based on menu state. -->
  <div class="sm:hidden" id="mobile-menu">
    <div class="space-y-1 pt-2 pb-3">
      <!-- Current: "border-indigo-500 bg-indigo-50 text-indigo-700", Default: "border-transparent text-gray-600 hover:border-gray-300 hover:bg-gray-50 hover:text-gray-800" -->
      <a href="#" class="block border-l-4 border-indigo-500 bg-indigo-50 py-2 pr-4 pl-3 text-base font-medium text-indigo-700" aria-current="page">Dashboard</a>
    </div>
  </div>
</nav>